<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-10-15T22:39:46Z" name="Default suite" finished-at="2018-10-15T22:39:53Z" duration-ms="6711">
    <groups>
    </groups>
    <test started-at="2018-10-15T22:39:46Z" name="Default test" finished-at="2018-10-15T22:39:53Z" duration-ms="6711">
      <class name="SeleniumTestRailMaven.SeleniumTestRailMaven.TestCase">
        <test-method is-config="true" signature="initSuite(java.lang.String)[pri:0, instance:SeleniumTestRailMaven.SeleniumTestRailMaven.TestCase@27462a88]" started-at="2018-10-15T22:39:45Z" name="initSuite" finished-at="2018-10-15T22:39:46Z" duration-ms="1236" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.google.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initSuite -->
        <test-method is-config="true" signature="getDriverForTest(java.lang.String)[pri:0, instance:SeleniumTestRailMaven.SeleniumTestRailMaven.TestCase@27462a88]" started-at="2018-10-15T22:39:46Z" name="getDriverForTest" finished-at="2018-10-15T22:39:51Z" duration-ms="4605" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDriverForTest -->
        <test-method signature="TestPass()[pri:0, instance:SeleniumTestRailMaven.SeleniumTestRailMaven.TestCase@27462a88]" started-at="2018-10-15T22:39:51Z" name="TestPass" finished-at="2018-10-15T22:39:51Z" duration-ms="7" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at SeleniumTestRailMaven.SeleniumTestRailMaven.TestCase.TestPass(TestCase.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestPass -->
        <test-method is-config="true" signature="logToTestRail(org.testng.ITestResult)[pri:0, instance:SeleniumTestRailMaven.SeleniumTestRailMaven.TestCase@27462a88]" started-at="2018-10-15T22:39:51Z" name="logToTestRail" finished-at="2018-10-15T22:39:52Z" duration-ms="1058" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TestPass status=FAILURE method=TestCase.TestPass()[pri:0, instance:SeleniumTestRailMaven.SeleniumTestRailMaven.TestCase@27462a88] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logToTestRail -->
        <test-method is-config="true" signature="stopDriver()[pri:0, instance:SeleniumTestRailMaven.SeleniumTestRailMaven.TestCase@27462a88]" started-at="2018-10-15T22:39:52Z" name="stopDriver" finished-at="2018-10-15T22:39:53Z" duration-ms="1011" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopDriver -->
      </class> <!-- SeleniumTestRailMaven.SeleniumTestRailMaven.TestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
